### ISSUE TITLE
Ensure config scrollbar only appears when necessary

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/fi-calc#183]
ty @city41 for bug report. ss from Chrome+Ubuntu:

![image](https://user-images.githubusercontent.com/2322305/81008860-7ad6c700-8e08-11ea-8787-f829e91f0110.png)

**Comment by jamesplease** [comment]
Should be fixed at https://staging.ficalc.app ! Thanks for the report @city41

**Comment by city41** [comment]
Looks good on staging, the scrollbar is gone for me.

**Comment by jamesplease** [comment]
Awesome! Thanks for checking 😁✌️
