### ISSUE TITLE
VPW bond rate is incorrect

### ISSUE THREAD

**Issue by jamejone** [jamesplease/fi-calc#259]
https://github.com/jamesplease/fi-calc/blob/1983c9b25fbf2467685483d9460748cb8efe47b9/src/vendor/%40moolah/withdrawal-strategies/utils/vpw-constants.ts#L20

The bond growth trend in the official spreadsheet is 1.9% (sheet 'Lists', cell B133):

https://www.bogleheads.org/wiki/Variable_percentage_withdrawal#VPW_Accumulation_And_Retirement_Worksheet

**Comment by jamesplease** [comment]
Good catch! I wonder how this happened 😜  Should be fixed now. Thanks @jamejone !

**Comment by jamejone** [comment]
Issue closed within 5 minutes. Impressive. 🤠
